### ISSUE TITLE
music.execQueue

### ISSUE THREAD

**Issue by Falkor8883** [BluSpring/discord.js-lavalink-musicbot#1]
When the play command is ran with a song in parameters it makes it way all the way to the **music.execQueue** function and the bot doesn't play any music, it sends the 2 embeds, 1 message, and leaves the voice channel. I logged the **queue[0]** and it shows as **undefined**.

**Comment by BluSpring** [comment]
Should've been fixed in the latest update. Forgot to close the issue though oops
